version: "3"

networks:
  test-wordpress-6.1.1-net:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: test-wordpress-6.1.1-mysql
    tty: true
    ports:
      - "0.0.0.0:4208:3306"
    volumes:
      - "./var/libclea/mysql/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - test-wordpress-6.1.1-net

  server:
    image: wordpress:latest
    container_name: test-wordpress-6.1.1
    ports:
      - "0.0.0.0:4282:80"
    volumes:
      - "./var/www/html/:/var/www/html"
    environment:
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mysql
    depends_on:
      - mysql
    networks:
      - test-wordpress-6.1.1-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ds-phpmyadmin
    ports:
      - "0.0.0.0:4283:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - test-wordpress-6.1.1-net
